<a href="https://colab.research.google.com/github/PANYAMLIKITHA/PYTHON-INTERACTIVE-LAB/blob/main/PYTHON_INTERACTIVE_LAB_2_11_09_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Employee:
    # class variables
    company_name = 'ABC Company'
    # constructor to initialize the object
    def __init__(self, name, salary):
        # instance variables
        self.name = name
        self.salary = salary
    # instance method
    def show(self):
        print('Employee:', self.name, self.salary, self.company_name)
# create first object
emp1 = Employee("Harry", 12000)
emp1.show()
# create second object
emp2 = Employee("Emma", 10000)
emp2.show()

Employee: Harry 12000 ABC Company
Employee: Emma 10000 ABC Company


In [ ]:
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.__salary = salary
    def show(self):
        print("Name is ", self.name, "and salary is", self.__salary)
emp = Employee("Jessa", 40000)
emp.show()
# access salary from outside of a class
# print(emp.__salary)

Name is  Jessa and salary is 40000


In [ ]:
# polymophism
class Circle:
    pi = 3.14
    def __init__(self, radius):
        self.radius = radius
    def calculate_area(self):
        print("Area of circle :", self.pi * self.radius * self.radius)

class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width
    def calculate_area(self):
        print("Area of Rectangle :", self.length * self.width)

# function def
def area(shape):
    # call action
    shape.calculate_area()

# create object
cir = Circle(5)
rect = Rectangle(10, 5)

# call common function
area(cir)
area(rect)

Area of circle : 78.5
Area of Rectangle : 50


In [ ]:
#inheritence
# Base class
class Vehicle:
    def __init__(self, name, color, price):
        self.name = name
        self.color = color
        self.price = price
    def info(self):
        print(self.name, self.color, self.price)
# Child class
class Car(Vehicle):
    def change_gear(self, no):
        print(self.name, 'change gear to number', no)
# Create object of Car
car = Car('BMW X1', 'Black', 35000)
car.info()
car.change_gear(5)

BMW X1 Black 35000
BMW X1 change gear to number 5


The built-in iter() function takes an arbitrary object and tries to return an iterator that will return the object’s contents or elements


In [ ]:
l=[1,2,3]
it=iter(l)
it.__next__()

1

In [ ]:
next(it)

2

In [ ]:
next(it)

3

In [ ]:
L = [1, 2, 3]
iterator = iter(L)

t = tuple(iterator)
t

(1, 2, 3)

In [ ]:
L = [1, 2, 3]
iterator = iter(L)
a, b, c = iterator
a, b, c

(1, 2, 3)

In [ ]:
m = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,

'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}

for key in m:
    print(key, m[key]) # Indented this line to be within the for loop

Jan 1
Feb 2
Mar 3
Apr 4
May 5
Jun 6
Jul 7
Aug 8
Sep 9
Oct 10
Nov 11
Dec 12


In [ ]:
L = [('Italy', 'Rome'), ('France', 'Paris'), ('US', 'Washington DC')]
dict(iter(L))

{'Italy': 'Rome', 'France': 'Paris', 'US': 'Washington DC'}

In [ ]:
s={6,7,8,9,13}
for i in s:
    print(i)

6
7
8
9
13


In [ ]:
seq1 = 'abc'
seq2 = (1, 2, 3)
[(x, y) for x in seq1 for y in seq2]

[('a', 1),
 ('a', 2),
 ('a', 3),
 ('b', 1),
 ('b', 2),
 ('b', 3),
 ('c', 1),
 ('c', 2),
 ('c', 3)]

In [ ]:
# Define the generator function
def generate_ints(n):
    for i in range(1, n + 1):
        yield i

gen = generate_ints(3)

print(next(gen))
# Expected output: 1
print(next(gen))
# Expected output: 2
print(next(gen))
# Expected output: 3
try:
    print(next(gen))
except StopIteration:
    print("StopIteration exception")
# Expected output: StopIteration exception

1
2
3
StopIteration exception


In [ ]:
import random
 # Generate 8 random numbers between [0, 10000)
rand_list = random.sample(range(10000), 8)
rand_list

[3786, 3582, 4643, 5023, 1902, 1228, 1397, 648]

In [ ]:
sorted(rand_list)

[648, 1228, 1397, 1902, 3582, 3786, 4643, 5023]

In [ ]:
sorted(rand_list, reverse=True)

[5023, 4643, 3786, 3582, 1902, 1397, 1228, 648]

In [ ]:
any([0, 1, 0])

True

In [ ]:
any([1, 1, 1])

True

In [ ]:
all([0, 1, 0])

False

In [ ]:
all([0, 0, 0])

False

In [ ]:
all([1, 1, 1])

True

In [ ]:
zip(['a', 'b', 'c'], (1, 2, 3))

In [ ]:
import itertools

for i in itertools.count(1):
  if i > 10:
    break
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
import itertools
list(itertools.islice(itertools.cycle([1, 2, 3, 4, 5]), 10))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
import itertools

itertools.cycle([1, 2, 3, 4, 5])
# This will create an iterator that cycles through the list indefinitely.
# To see the output, you would need to iterate over it.
# For example:
# for i in itertools.cycle([1, 2, 3, 4, 5]):
#     print(i)

In [ ]:
import itertools

list(itertools.repeat('abc', 10))

['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']

In [ ]:
#numpy
import numpy as np
x=np.random.randint(10,30,6)
print(x)

[28 22 19 28 20 27]


In [ ]:
import numpy as np
x=np.random.randint(0,10,40)
print(x)

[2 5 2 2 9 0 5 5 5 0 2 3 5 8 7 8 0 4 7 1 7 2 8 1 8 2 6 2 6 6 3 6 1 0 8 7 7
 7 2 6]


In [ ]:
# a.Using List or Tuple
import numpy as np
a = np.array([2,3,4])   #using list, 1-D Array
print(type(a))          #<type ‘numpy.ndarray’>

<class 'numpy.ndarray'>


In [ ]:
# b.Creating 2D array
a = np.array([[1,3,5],[2,4,6]])
print(a[0][0])

1


In [ ]:
# c.Defining the type of array
a = np.array([[1,2],[3,4]],dtype=complex)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# d.Methods to create arrays with placeholder values
arr = np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr= np.ones((3,3),int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr= np.empty((3,4))
print(arr)                #uninitialized garbage value

[[6.75907739e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
# e.Using arange function
arr= np.arange(10, 30, 5)
print(arr)

[10 15 20 25]


In [ ]:
arr= np.arange(0, 2, 0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
# f.To create ‘n’ numbers from the defined range.
arr = np.linspace(0, 2, 9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# g.To create Identity Matrix
arr = np.identity(3, int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#To concatenate arrays
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
print(np.concatenate([a,b,c]))

[1 2 3 4 5 6]


In [ ]:
# To concatenate arrays (row-wise / col-wise)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)          #[[1,2][3,4][5,6][7,8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a, b), axis=1)          #[[1,2,5,6], [3,4,7,8]]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# To find index of maximum and minimum element:
A = np.array([2, 1, 4, 9])
print(A.argmin())
print(A.argmax())

1
3


In [ ]:
# for multidimensional array, we have to provide axis value also.
A = np.array([[3, 2], [5, 6]])
print(A.argmin(axis=0))                 #[0, 0]
print(A.argmin(axis=1))                 #[1, 0]
print(A.argmax(axis=0))                 #[1, 1]
print(A.argmax(axis=1))                 #[0, 1]

[0 0]
[1 0]
[1 1]
[0 1]


In [ ]:
# Sorting of array:
A = np.array([6, 2, 5, -1, 0])
print(np.sort(A))#[-1, 0, 2, 5, 6]

[-1  0  2  5  6]


In [ ]:
# Unique elements:
A = np.array([1, 1, 4, 5, 5, 7])
print(np.unique(A))#[1, 4, 5, 7]

[1 4 5 7]


In [ ]:
# Diagonal elements of 2D array:
A = np.array([[1, 2], [3, 4]])
print(A.diagonal())#[1, 4]

[1 4]


In [ ]:
# Indexing/Slicing:
A = np.arange(10) ** 3
print(A)

A[2:5]

[  0   1   8  27  64 125 216 343 512 729]


array([ 8, 27, 64])

In [ ]:
A[0: 6: 2]= -100
print(A)

[-100    1 -100   27 -100  125  216  343  512  729]


In [ ]:
A[ : :-1]

In [ ]:
# Transpose:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
